import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
  <>
    <Head>
      <title>トップページ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    {/* ヘッダー */}
    {/* ヘッダー下の帯 */}
    {/* 見出し */}
    {/* information */}
    {/* 2nd chat room */}
    {/* 特集チケット */}
    {/* 2nd ランキング */}
    {/* フッター */}
    <div>トップページ WIP</div>
  </>
);

export default Home;
