import type { NextPage } from 'next';
import Head from 'next/head';

import { HeaderGuide, Footer } from '@/src/components/ui-elements';
import {
  TopWelcomeBoard,
  TopInformationBoard,
  TopFeatureBoard,
  Header,
} from '@/src/components/ui-parts';

const Top: NextPage = () => (
  <>
    <Head>
      <title>トップページ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    {/* ヘッダー */}
    <Header />
    {/* ヘッダー下の帯 */}
    <HeaderGuide color='primary'>
      Ticketnoteは「プログラミング学習を記録・共有」する無料サービスです
    </HeaderGuide>
    {/* 見出し */}
    <TopWelcomeBoard />
    {/* information */}
    <TopInformationBoard />
    {/* 2nd chat room */}
    {/* 特集チケット */}
    <TopFeatureBoard />
    {/* 2nd ランキング */}
    {/* フッター */}
    <Footer />
  </>
);

export default Top;
