import type { NextPage } from 'next';
import Head from 'next/head';

import { Header, HeaderGuide, Footer } from '@/src/components/ui-elements';
import { TopWelcomeBoard, TopInformationBoard, TopFeatureBoard } from '@/src/components/ui-parts';

const Top: NextPage = () => (
  <>
    <Head>
      <title>トップページ</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    {/* ヘッダー */}
    <Header />
    {/* ヘッダー下の帯 */}
    <HeaderGuide />
    {/* 見出し */}
    <TopWelcomeBoard />
    {/* information */}
    <TopInformationBoard />
    {/* 2nd chat room */}
    {/* 特集チケット */}
    <TopFeatureBoard />
    {/* 2nd ランキング */}
    {/* フッター */}
    <Footer />
  </>
);

export default Top;
